# Generated by Django 2.2.6 on 2019-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
