# Generated by Django 2.2.6 on 2019-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
