# Generated by Django 2.2.6 on 2019-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
