# Generated by Django 2.2.6 on 2019-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='entry_code',
            field=models.IntegerField(default=4880),
        ),
    ]
