# Generated by Django 2.2.6 on 2019-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_item_is_live_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auction_type',
            field=models.CharField(choices=[('live', 'live'), ('silent', 'silent')], default='silent', max_length=6),
        ),
    ]
