# Generated by Django 2.2.6 on 2019-11-04 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191030_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default_item_pic.jpg', upload_to='static/auction/auction_pics'),
        ),
        migrations.AddField(
            model_name='auction',
            name='participants',
            field=models.ManyToManyField(related_name='joined_auctions', related_query_name='joined_auction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_pic',
            field=models.ImageField(default='default_item_pic.jpg', upload_to='static/auction/item_pics'),
        ),
    ]
