# Generated by Django 2.2.6 on 2019-10-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20191023_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='entry_code',
            field=models.IntegerField(default=33825),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starting_price', models.FloatField()),
                ('item_desc', models.TextField(verbose_name='item description')),
                ('is_sold', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('paid_time', models.DateTimeField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
    ]
