# Generated by Django 2.2.6 on 2019-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_item_is_live_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='defaults/default_item_pic.jpg', upload_to='item_pics'),
        ),
    ]
