# Generated by Django 2.2.6 on 2019-10-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20191023_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='entry_code',
            field=models.IntegerField(default=50405),
        ),
        migrations.AlterField(
            model_name='item',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
