# Generated by Django 2.2.6 on 2019-10-25 03:18

import auction.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20191023_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='entry_code',
            field=models.IntegerField(default=auction.models.random_entry_code),
        ),
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.User'),
        ),
    ]
