# Generated by Django 2.2.6 on 2019-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_item_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_pic',
            field=models.ImageField(default='default_item_pic.jpg', upload_to='item_pics'),
        ),
    ]
