# Generated by Django 2.2.6 on 2019-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20191025_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
